modLoader = "javafml"
loaderVersion = "[41,)"
license = "MIT"

[[mods]]
modId = "improbable_plot_machine"
version = "${version}"
displayName = "improbable_plot_machine"
description = '''
magik
'''

[[dependencies.improbable_plot_machine]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.improbable_plot_machine]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"
