@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.implom.common.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;