package arekkuusu.implom;

public class LibNames {

	public static final String CRYSTAL_PRISM = "crystal_prism";
	public static final String MONOLITHIC = "monolithic";
	public static final String MONOLITHIC_GLYPH = "monolithic_glyph";
	public static final String LARGE_POT = "large_pot";
	public static final String IMBUED_QUARTZ = "imbued_quartz";
	public static final String CRYSTAL_SHARD = "crystal_shard";
	public static final String QUARTZ = "quartz";
	public static final String MAGNETIC_BOLT = "magnetic_bolt";
	public static final String MAGNETIC_GEAR = "magnetic_gear";
	public static final String MAGNETIC_SPRING = "magnetic_spring";
	public static final String CLOCKWORK = "clockwork";
	public static final String BOUND_PHOTON = "bound_photon";
	public static final String MAINSPRING_MECHANISM = "mainspring_mechanism";
	public static final String FRAME_CORE = "frame_core";
	public static final String SOLENOID = "solenoid";
	public static final String RESISTOR = "resistor";
	public static final String CAPACITOR = "capacitor";
	public static final String INDUCTOR = "inductor";
	public static final String GOLD_PLATE = "gold_plate";
	public static final String MAGNETIC_PLATE = "magnetic_plate";
	public static final String MAGNETIC_ACTUATOR = "magnetic_actuator";
	public static final String ELECTROMAGNET = "electromagnet";
	public static final String INTRINSIC_CAPACITOR = "intrinsic_capacitor";
	public static final String FIRE_BRICK = "fire_brick";
	public static final String FIRE_BRICK_PLATE = "fire_brick_plate";
	public static final String FIRE_CLAY = "fire_clay";
	public static final String FIRE_CLAY_BRICK = "fire_clay_brick";
	public static final String FIRE_CLAY_PLATE = "fire_clay_plate";
	public static final String MOMENTUM_OSCILLATOR = "momentum_oscillator";
	public static final String HOT_AIR = "hot_air";
	public static final String FIRE_CLAY_BLOCK = "fire_clay_block";
	public static final String FIRE_BRICK_BLOCK = "fire_brick_block";
	public static final String FIRE_BRICKS = "fire_bricks";
	public static final String FIRE_BRICKS_GLASS = "fire_bricks_glass";
	public static final String FIRE_BRICKS_WINDOW = "fire_bricks_window";
	public static final String BLAST_FURNACE_CONTROLLER = "blast_furnace_controller";
	public static final String BLAST_FURNACE_DRAIN = "blast_furnace_drain";
	public static final String BLAST_FURNACE_FILTER = "blast_furnace_filter";
	public static final String BLAST_FURNACE_INPUT = "blast_furnace_input";
	public static final String BLAST_FURNACE_TUYERE = "blast_furnace_tuyere";
	public static final String BLAST_FURNACE_AIR_VENT = "blast_furnace_air_vent";
	public static final String BLAST_FURNACE_PIPE = "blast_furnace_pipe";
	public static final String BLAST_FURNACE_AIR_PUMP = "blast_furnace_air_pump";
	public static final String BLAST_FURNACE_HEATER = "blast_furnace_heater";
	public static final String BLAST_FURNACE_PIPE_GAUGE = "blast_furnace_pipe_gauge";
}
