@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.implom.client.effect;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;