@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.solar.common.network;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;